# RubyDrop configuration file, should be pretty straightforward

# Lets you turn debugging mode on and off
git_debug: false
rubydrop_debug: true

# The local filepath where you want to monitor files
rubydrop_root: ~/RubyDrop

# The address of the server you would like to sync with
remote_addr: meltingice.net

# ... and the port
remote_port: 6789